
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_DATABASE}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
